Implement Le parameter handling in select command
makinako/OpenFIPS201 pull request #39
Opened 2021-07-09 18:12 UTC by spaikmos

ISO 7816-4 section 7.1.1 specifies:

If the Le field contains only bytes set to '00', then all the bytes corresponding to the selection option should be
returned within the limit of 256 for a short Le field, or 65 536 for an extended Le field. If the Le field is absent,
i.e., for returning no file control information, then the response data field shall also be absent.

The original code ignores the Le value and sends the PIV APT regardless of what Le was specified.  This change 
enables the following behavior:

1)  If no Le is sent, then status 0x9000 is sent to indicate the applet was properly selected.
2)  If Le = 0x00 is sent, then the default PIV APT is returned.
3)  Any other Le value (0x01 - 0xFF) is treated as an error.

2021-07-12 00:11 UTC, makinako requested changes
Thanks for the find! Yes it's definitely incorrect to return FCI data in case where the LE is absent. I'm going to add a comms unit test layer to all commands for this as appropriate.

One comment is that the piv.select() must always be called to process the PIV rules, regardless of whether the user requests FCI response data.

See suggestion below, which includes FCI's that are < 256 but still large enough for the FCI buffer (to catch older readers that have smaller buffers):
```
    // STEP 1 - Call the PIV 'SELECT' command in all cases to handle the PIV SELECT rules
    length = piv.select(buffer, ISO7816.OFFSET_CDATA, length);    

    // STEP 2 - Check the le value    
    if (le == 0) {
      // The caller has not requested FCI data
      length = 0;
    }
    // The caller must be able to handle the full FCI + SW12
    else if (le < (length + (short)2)) {
      ISO7816.throwIt(ISO7816.SW_WRONG_LENGTH);
    }

    // Return the FCI data (if requested)
    if (length > 0) {
      apdu.setOutgoingLength(length);
      apdu.sendBytes(ISO7816.OFFSET_CDATA, length);      
    }

```

2021-07-12 02:13 UTC, spaikmos commented
Ok.

Reading further into ISO 7816-3, it seems that I need to send a different
status code if Le is too small (0x6CXX).  From the spec, Le only pertains
to the data length; it should not include the status code so no need to add
2 to the length.

I'll make the mods and resubmit to you.  Thanks!

On Sun, Jul 11, 2021 at 5:11 PM makinako ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for the find! Yes it's definitely incorrect to return FCI data in
> case where the LE is absent. I'm going to add a comms unit test layer to
> all commands for this as appropriate.
>
> One comment is that the piv.select() must always be called to process the
> PIV rules, regardless of whether the user requests FCI response data.
>
> See suggestion below, which includes FCI's that are < 256 but still large
> enough for the FCI buffer (to catch older readers that have smaller
> buffers):
>
>     // STEP 1 - Call the PIV 'SELECT' command in all cases to handle the PIV SELECT rules
>     length = piv.select(buffer, ISO7816.OFFSET_CDATA, length);
>
>     // STEP 2 - Check the le value
>     if (le == 0) {
>       // The caller has not requested FCI data
>       length = 0;
>     }
>     // The caller must be able to handle the full FCI + SW12
>     else if (le < (length + (short)2)) {
>       ISO7816.throwIt(ISO7816.SW_WRONG_LENGTH);
>     }
>
>     // Return the FCI data (if requested)
>     if (length > 0) {
>       apdu.setOutgoingLength(length);
>       apdu.sendBytes(ISO7816.OFFSET_CDATA, length);
>     }
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/makinako/OpenFIPS201/pull/39#pullrequestreview-703639273>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA2RIMV6MFGTX5VUQ7EGH4LTXIXLDANCNFSM5ADG6J6A>
> .
>

2021-07-12 19:16 UTC, dengert commented
In "// STEP 2 - Check the le value"
ISO 7816-4 says in Table 1:
"Le field      |     Absent for encoding Ne = 0, present for encoding Ne > 0   |   0, 1, 2 or 3"

Do you really mean Ne? 

Your code should not be dealing directly with Le. Ne is the result of converting short and extended Le values. Short APDUs, Le = 0x00 means send as much as you can and with extended Le = 0X00, 0x00, 0x00 means send 65,536  

The conversion of Le to Ne should be handled by the Java code just like any other command and send as much as you can, and return status '61xx"  where xx=00 means there is more then 256 bytes left should be handled like any other command, and a get-response can be used to get more.  

And "table 5" says for `61XX`:  
"SW2 encodes the number of data bytes still available (see text below)(see below)"

The below says:
"Two interindustry values of SW1 are independent from any transmission protocol.
--- If SW1 is set to '61', then the process is completed and before issuing any other command, a GET RESPONSE command may be issued with the same CLA and using SW2 (number of data bytes still available) as short Le field.
---  If SW1 is set to '6C', then the process is aborted and before issuing any other command, the same command may be re-issued using SW2 (exact number of available data bytes) as short Le field"

2021-07-12 21:30 UTC, spaikmos commented
Thanks for clarifying the difference between Ne and Le.  I agree that Ne is what was intended, and I've updated the code.

I found some interesting behavior.  When using the 0x61xx return code, it seems that the smart card sends 0x9000.  I'm not sure  what is coverting 0x61xx to 0x9000, but it happens consistently.

One question I am wondering is if I should return partial APT if Ne is less than the actual APT length?  Some of the NIST test cards behave this way.  For example, if Le = Ne = 10 bytes, then the select() command will return the first 10 bytes, along with a 0x9000 (not 0x61xx) status code.  

This is very confusing!  FWIW, it feels like this behavior is ill-defined and most likely varies by manufacturer.  In the code, I simply return 0x61xx if it Ne is too small, to indicate the command was processed correctly.  In *my* card, this gets converted to 0x9000.  Also, I believe 0x61xx indicates that the next command can be a get response to get the rest of the data, and this likely will fail unless we store the data on the card.

Thoughts?

2021-07-12 22:54 UTC, dengert commented
I am not a java programmer, but what looks wrong to me is the line:

apdu.sendBytes(ISO7816.OFFSET_CDATA, length); 

The ISO7816.OFFSET_CDATA would be the Lc data sent by the application to the card applet.

What needs to be returned includes the AID and is DER encoded with other data.

For example with a real NIST demo card from 2006 
```
opensc-tool -c default -s '00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00'
(Lc is 09.  The last 00 is the Le) 
Sending: 00 A4 04 00 09 A0 00 00 03 08 00 00 10 00 00
Received (SW1=0x90, SW2=0x00):
61 39 4F 0B A0 00 00 03 08 00 00 10 00 01 00 79 a9O............y
07 4F 05 A0 00 00 03 08 50 0E 49 44 2D 4F 6E 65 .O......P.ID-One
20 50 49 56 20 42 49 4F 5F 50 10 77 77 77 2E 6F  PIV BIO_P.www.o
62 65 72 74 68 75 72 2E 63 6F 6D 7F 66 08 02 02 berthur.com.f...
80 00 02 02 80 00
```

So what it looks like your code will return just what the application sent:  `A0 00 00 03 08 00 00 10 00 and status 90 00' 

Note the PIV SELECT is a SELECT FILE with special meaning:
See ISO 7816-4 Section "8.2.1.2 Application identifier" and 8.2.1.3 Application template which says:
"Referenced by tag '61', this interindustry template may be present in EF.ATR (see 8.2.1.1), in EF.DIR (see 8.2.1.1) and in the management data of any DF (see 5.3.3)."

See NIST sp800-73-4 Part 2 3.1.1 SELECT Card Command:
"Upon selection, the PIV Card Application shall return the application property template described in Table 3.
Table 3. Data Objects in the PIV Card Application Property Template (Tag '61')"

AND the java card will always look for   `00 A4 04 00` with an AID and use it to select the applet,
But it is up to the applet to return the appropriate data. It the case of PIV
"PIV Card Application Property Template (Tag '61')"

The applet should have this template ready to return. I don't see it.

2021-07-12 23:22 UTC, spaikmos commented
Hi Doug,

The APT data is populated by this line:

``` java
length = piv.select(buffer, ISO7816.OFFSET_CDATA, length);
```

If you look at PIV.java, you will see this code:

``` java
  public short select(byte[] buffer, short offset, short length) {

    //
    // PRE-CONDITIONS
    //

    // NONE

    //
    // EXECUTION STEPS
    //

    // STEP 1 - Return the APT
    Util.arrayCopyNonAtomic(
        Config.DEFAULT_APT, (short) 0, buffer, offset, (short) Config.DEFAULT_APT.length);

    return (short) Config.DEFAULT_APT.length;
  }
```

This code is copying the DEFAULT_APT into the apdu buffer.  DEFAULT_APT is defined in Config.java and has the format you listed.

I agree, the way the APDU is handled in Java is odd, but that's how the SDK works.  The documentation for [SendBytes()](https://docs.oracle.com/javacard/3.0.5/api/javacard/framework/APDU.html#sendBytes(short,%20short)) shows that the reply buffer re-uses the same apdu buffer.

I left the index based on the original code, which placed the APT data starting from OFFSET_CDATA, as you noted.  Not sure why that was originally done that way; I can only guess that the original intent was for the piv.select() function to parse this data and react to it, but as you can see, the function simply copies the DEFAULT_APT into the buffer.

2021-07-13 00:54 UTC, makinako commented
> This code is copying the DEFAULT_APT into the apdu buffer. DEFAULT_APT is defined in Config.java and has the format you listed.
Yes this is correct and re-use of the APDU buffer totally normal in JC. 

> I left the index based on the original code, which placed the APT data starting from OFFSET_CDATA, as you noted. Not sure why that was originally done that way;
There is no reason why we need to pass through `ISO7816.OFFSET_CDATA` as the offset now that I think about it. passing `(short)0` is totally fine. It was done that way because the tests still passed :)

> One question I am wondering is if I should return partial APT if Ne is less than the actual APT length? Some of the NIST test cards behave this way. For example, if Le = Ne = 10 bytes, then the select() command will return the first 10 bytes, along with a 0x9000 (not 0x61xx) status code.
I've run this against the latest V2 NIST test cards and the behaviour is the same. It truncates the response if the value supplied by LE is insufficient. It does not return 6Cxx and does not attempt to chain the response using 61XX. Since this does vary by manufacturer, in the absence of clear direction I vote we do what the reference cards do.

**TEST 1 - SELECT PIV with LE == 00**
```
  Command APDU:
    00 A4 04 00 0B A0 00 00 03 08 00 00 10 00 01 00
    00
  Response APDU:
    61 2A 4F 0B A0 00 00 03 08 00 00 10 00 01 00 79
    07 4F 05 A0 00 00 03 08 50 0A 49 44 2D 4F 6E 65
    20 50 49 56 AC 06 80 01 27 06 01 00 7F 66 08 02
    02 03 F8 02 02 7F FF 90 00

```
**TEST 2 - SELECT PIV with LE not present**
```
  Command APDU:
    00 A4 04 00 0B A0 00 00 03 08 00 00 10 00 01 00
  Response APDU:
    90 00

```

**TEST 3 - SELECT PIV with LE == 10 (insufficient buffer to hold entire FCI)**
```
 Command APDU:
    00 A4 04 00 0B A0 00 00 03 08 00 00 10 00 01 00
    10
 Response APDU:
    61 2A 4F 0B A0 00 00 03 08 00 00 10 00 01 00 79
    90 00

```

2021-07-13 01:11 UTC, spaikmos commented
Ok.  That makes things easier.  I'm not sure if the commits I uploaded are correct (forgive me - I'm new to github).  If there's an easier way to squash the commits into one CL, please help me!  I hope the code is ok now.

2021-07-13 01:19 UTC, makinako approved these changes
This will do the job.

2021-07-13 01:19 UTC, merged